[package]
name = "chip8-emu"
version = "0.1.0"
authors = ["ryskov"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.18"
rand = "0.7.3"
pixels = "0.2.0"
winit = "0.22.2"
winit_input_helper = "0.7.0"
